### ISSUE TITLE
Consider using phpDoc

### ISSUE THREAD

**Issue by javiereguiluz** [Simettric/SimpleForm#4]
Right now some files display metainformation that could be considered inappropriate for a public project. For instance:

```
/**
 * Created by PhpStorm.
 * User: Asier
 * Date: 5/08/14
 * Time: 18:02
 */
```

I know that this is an ultra-low priority task right now, but in the future you should consider switching to phpDoc:

```
/**
 * (The explanation of this class ...)
 *
 * @author Asier Marqués <asiermarques@gmail.com>
 */
```

**Comment by javiereguiluz** [comment]
Closing this ancient issue as "won't fix".

**Comment by asiermarques** [comment]
This is fixed in dev-master
