### ISSUE TITLE
Consider following a code syntax standard

### ISSUE THREAD

**Issue by javiereguiluz** [Simettric/SimpleForm#5]
Reading the source code of this project is sometimes hard because it seems that it doesn't follow any common code syntax standard. In the past, refactoring an existing project to follow a standard was a huge task, but thanks to the great [PHP-CS-Fixer](https://github.com/fabpot/PHP-CS-Fixer) project, now you just have to execute one command and all the project source code is fixed (without breaking it!). You can even [integrate it with PHPStorm](http://arnolog.net/post/92715936483/use-fabpots-php-cs-fixer-tool-in-phpstorm-in-2-steps).

**Comment by javiereguiluz** [comment]
Closing this ancient issue as "won't fix".

**Comment by asiermarques** [comment]
This must be fixed now.
